version: '3'
# DOC https://hub.docker.com/_/wordpress

services:

  wordpress:
    image: wordpress:php8.0-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    depends_on:
      - db
    volumes:
      - /wordpress:/var/www/html


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9095:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER_ROOT}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql


volumes:
# Permet de définir un volume réutilisables par plusieurs services au lieu de le définir
# en tant que sous clé de tous les services, on le définit une fois ici
  wordpress:
  db:
